FROM mcr.microsoft.com/dotnet/sdk:7.0 as build
WORKDIR /app

RUN apt-get update && apt-get install -y clang zlib1g-dev libkrb5-dev llvm

COPY . ./
RUN dotnet restore
RUN dotnet publish \
        -c Release \
        -o out \
        --runtime linux-x64 \
        -p:PublishTrimmed=true \
        -p:PublishAot=true \
        -p:StripSymbols=true \
        -p:IlcOptimizationPreference=size \
        -p:IlcDisableReflection=true \
        -p:IlcGenerateStackTraceData=false \
        -p:InvariantGlobalization=true \
        -p:PublishStaticLinked=true

FROM scratch
WORKDIR /app

COPY --from=build /app/out/smaller-images .

ENTRYPOINT ["./smaller-images"]