FROM mcr.microsoft.com/dotnet/sdk:7.0 as build
WORKDIR /app

RUN apt-get update && apt-get install clang zlib1g-dev -y

COPY . ./
RUN dotnet restore
RUN dotnet publish -c Release -o out --runtime linux-x64 -p:PublishTrimmed=true -p:PublishAot=true

FROM scratch
WORKDIR /app
COPY --from=build /app/out .

ENTRYPOINT ["./smaller-images"]