FROM mcr.microsoft.com/dotnet/sdk:7.0 as build
WORKDIR /app

COPY . ./
RUN dotnet restore --runtime alpine-x64
RUN dotnet publish -c Release -o out --runtime alpine-x64 --self-contained -p:PublishTrimmed=true

FROM mcr.microsoft.com/dotnet/runtime-deps:7.0-alpine
WORKDIR /app
COPY --from=build /app/out .

ENTRYPOINT ["./smaller-images"]