FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
WORKDIR /app

RUN apk add clang binutils musl-dev build-base zlib-static

COPY . ./
RUN dotnet restore --runtime linux-musl-x64
RUN dotnet publish \
        -c Release \
        -o out \
        --runtime linux-musl-x64 \
        --self-contained true \
        -p:PublishTrimmed=true \
        -p:PublishAot=true \
        -p:StripSymbols=true \
        -p:IlcOptimizationPreference=size \
        -p:IlcDisableReflection=true \
        -p:IlcGenerateStackTraceData=false \
        -p:InvariantGlobalization=true \
        -p:StaticExecutable=true \
        -p:StaticallyLinked=true

FROM scratch
WORKDIR /app

COPY --from=build /app/out .

ENTRYPOINT ["/app/smaller-images"]