FROM mcr.microsoft.com/dotnet/sdk:7.0-alpine AS build
WORKDIR /app

RUN apk add clang gcc lld musl-dev build-base zlib-dev

COPY . ./
RUN dotnet restore
RUN dotnet publish -c Release -o out --runtime linux-musl-x64 -p:PublishTrimmed=true -p:PublishAot=true

FROM mcr.microsoft.com/dotnet/runtime-deps:7.0-alpine
WORKDIR /app
COPY --from=build /app/out .

ENTRYPOINT ["./smaller-images"]